# sdk image
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS builder

WORKDIR /src
COPY src .

RUN dotnet restore Server/Server.csproj
RUN dotnet build Server/Server.csproj
RUN dotnet publish -c Release -o /publish Server/Server.csproj

# app image
FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /app
COPY --from=builder /publish/ .

EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "Server.dll"]
